name: "action-foreach"
description: "Run GitHub action on a list of repos."
author: "Purdue ECE"
inputs:
  workdir:
    description: "Working directory to clone repos to."
    default: "action-foreach-repos"
  repos:
    description: "List of repos to run action for."
    required: true
  workflow:
    description: "Workflow YAML file contents to run on each repo."
    required: true
runs:
  using: "docker"
  image: "Dockerfile"