##############################
# Author: Denny Nowak
# Email:  nowak32@purdue.edu
# ID:     ee364b14
# Date:   03/03/2022
##############################

name: Python application

on: 
  push:
    paths:
      - 'Prelab08/**'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest and build coverage file
      run: |
        pytest --cov-report term --cov=. Prelab08/tests/testMain.py --cov-report=html
