env:
  REPO: PurdueECE364/prelabs-moffatw
  REPO_DIR: test_data/run-20220410_200512/PurdueECE364-prelabs-moffatw
name: Pylint Test
on: [push]
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: PurdueECE/action-pylint@main
        with:
          path: ${{ env.REPO_DIR }}/Prelab06
