name: Dircheck Test - PurdueECE364-prelabs-siddmitra10
on:
  workflow_run:
      workflows: [Dircheck Test]
env:
  REPO: PurdueECE364/prelabs-siddmitra10
  REPO_DIR: test_data/run-20220411_182137/PurdueECE364-prelabs-siddmitra10
jobs:
  test_dircheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: PurdueECE/action-dircheck@main
        with:
          paths: $REPO_DIR/Prelab06
