env:
  REPO: PurdueECE364/prelabs-moffatw
  REPO_DIR: test_data/run-20220410_200012/PurdueECE364-prelabs-moffatw
name: Print Test
on: [push]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: "echo repo: ${{ env.REPO_DIR }}"
