name: Dircheck Test - PurdueECE364-prelabs-KevinMi2023p
on:
  workflow_run:
      workflows: [Dircheck Test]
env:
  REPO: PurdueECE364/prelabs-KevinMi2023p
  REPO_DIR: test_data/run-20220411_180859/PurdueECE364-prelabs-KevinMi2023p
jobs:
  test_dircheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: $REPO
          token: $SECRETS_PAT
      - uses: PurdueECE/action-dircheck@main
        with:
          paths: Prelab06
