name: Dircheck Test - PurdueECE364-prelabs-moffatw
on:
  workflow_run:
      workflows: [Dircheck Test]
env:
  REPO: PurdueECE364/prelabs-moffatw
  REPO_DIR: test_data/PurdueECE364-prelabs-moffatw
jobs:
  test_dircheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: PurdueECE/action-dircheck@main
        with:
          paths: $REPO_DIR/Prelab06
