name: Foreach - Print Test
on: [workflow_dispatch]

jobs:
  test_print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      # - id: get_repos
      #   uses: PurdueECE/action-find-repos@v1.1
      #   with:
      #     org: PurdueECE364
      #     pattern: ^prelabs-.*$
      #     created_after: '01/01/2022 00:00:00'
      #     created_before: '01/06/2022 00:00:00'
      #     token: ${{ secrets.PAT }}
      - uses: ./
        with:
          token: ${{ secrets.PAT }}
          repos: PurdueECE364/prelabs-moffatw
          workdir: test_data
          workflow: >
            name: Print Test
            on: [push]
            jobs:
              print:
                runs-on: ubuntu-latest
                steps:
                  - run: echo "repo = ${{ env.REPO }}"